version: '3.8'

services:
  # PHP Servisi
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kurye-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - kurye-network

  # Nginx Web Sunucusu
  nginx:
    image: nginx:1.21-alpine
    container_name: kurye-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - kurye-network

networks:
  kurye-network:
    driver: bridge